// <auto-generated>
// 이 파일은 SoundDefineGenerator에 의해 자동 생성되었습니다.
// 리소스 폴더의 사운드 파일이 변경될 때마다 자동 갱신됩니다.
// </auto-generated>

namespace GameArifiction.Core.Audio
{
    /// <summary>
    /// [기능]: 사운드 리소스 경로 디파인 상수 모음
    /// [작성자]: 윤승종
    /// </summary>
    public static class SoundDefine
    {
        public const string Dummy_click = "Sounds/SFX/dummy_click";
        public const string Bgm_claw = "Sounds/BGM/ClawMachine/bgm_claw";
        public const string Bgm_graderunner_phase1 = "Sounds/BGM/GradeRunner/bgm_graderunner_phase1";
        public const string Bgm_graderunner_phase2 = "Sounds/BGM/GradeRunner/bgm_graderunner_phase2";
        public const string Lobby_Bgm = "Sounds/BGM/Lobby/Lobby_Bgm";
        public const string Sfx_claw_catch = "Sounds/SFX/ClawMachine/sfx_claw_catch";
        public const string Sfx_claw_clear = "Sounds/SFX/ClawMachine/sfx_claw_clear";
        public const string Sfx_claw_crane = "Sounds/SFX/ClawMachine/sfx_claw_crane";
        public const string Sfx_claw_fail = "Sounds/SFX/ClawMachine/sfx_claw_fail";
        public const string Sfx_claw_question = "Sounds/SFX/ClawMachine/sfx_claw_question";
        public const string Sfx_claw_start = "Sounds/SFX/ClawMachine/sfx_claw_start";
        public const string Sfx_claw_success = "Sounds/SFX/ClawMachine/sfx_claw_success";
        public const string Sfx_claw_touch = "Sounds/SFX/ClawMachine/sfx_claw_touch";
        public const string Sfx_graderunner_cheatsheet = "Sounds/SFX/GradeRunner/sfx_graderunner_cheatsheet";
        public const string Sfx_graderunner_hit = "Sounds/SFX/GradeRunner/sfx_graderunner_hit";
    }
}
