#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text;
using System.Linq;

namespace GameArifiction.Core.Audio.Editor
{
    /// <summary>
    /// [기능]: Resources/Sounds 폴더 내의 오디오 파일을 감지하여 SoundDefine.cs 코드를 자동 생성합니다.
    /// [작성자]: 윤승종
    /// </summary>
    public class SoundDefineGenerator : AssetPostprocessor
    {
        private const string SOUND_FOLDER_PATH = "Assets/_Game/Resources/Sounds";
        private const string OUTPUT_FILE_PATH = "Assets/_Game/Scripts/Core/Audio/SoundDefine.cs";

        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            bool shouldGenerate = false;

            foreach (var path in importedAssets.Concat(deletedAssets).Concat(movedAssets))
            {
                if (path.StartsWith(SOUND_FOLDER_PATH))
                {
                    shouldGenerate = true;
                    break;
                }
            }

            if (shouldGenerate)
            {
                GenerateDefineFile();
            }
        }

        [MenuItem("GameArifiction/Audio/Generate Sound Defines")]
        public static void GenerateDefineFile()
        {
            if (!Directory.Exists(SOUND_FOLDER_PATH))
            {
                Debug.LogWarning($"[SoundDefineGenerator] 사운드 폴더를 찾을 수 없습니다: {SOUND_FOLDER_PATH}");
                return;
            }

            string[] audioExtensions = { ".wav", ".mp3", ".ogg" };
            var audioFiles = Directory.GetFiles(SOUND_FOLDER_PATH, "*.*", SearchOption.AllDirectories)
                                      .Where(f => audioExtensions.Contains(Path.GetExtension(f).ToLower()))
                                      .Select(f => f.Replace("\\", "/"))
                                      .ToArray();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// 이 파일은 SoundDefineGenerator에 의해 자동 생성되었습니다.");
            sb.AppendLine("// 리소스 폴더의 사운드 파일이 변경될 때마다 자동 갱신됩니다.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace GameArifiction.Core.Audio");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// [기능]: 사운드 리소스 경로 디파인 상수 모음");
            sb.AppendLine("    /// [작성자]: 윤승종");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class SoundDefine");
            sb.AppendLine("    {");

            foreach (var file in audioFiles)
            {
                int resourcesIndex = file.IndexOf("Resources/");
                if (resourcesIndex >= 0)
                {
                    string relativePath = file.Substring(resourcesIndex + "Resources/".Length);
                    string pathWithoutExtension = relativePath.Substring(0, relativePath.LastIndexOf('.'));
                    string fileName = Path.GetFileNameWithoutExtension(file);

                    string safeVarName = new string(fileName.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());
                    if (string.IsNullOrEmpty(safeVarName)) continue;
                    
                    // 첫 글자를 대문자로 변경하여 catch 등 C# 예약어와의 충돌 방지
                    safeVarName = char.ToUpper(safeVarName[0]) + safeVarName.Substring(1);
                    
                    if (char.IsDigit(safeVarName[0])) safeVarName = "_" + safeVarName;

                    sb.AppendLine($"        public const string {safeVarName} = \"{pathWithoutExtension}\";");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string dir = Path.GetDirectoryName(OUTPUT_FILE_PATH);
            if (!Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllText(OUTPUT_FILE_PATH, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();
            Debug.Log("[SoundDefineGenerator] SoundDefine.cs 파일이 성공적으로 생성/갱신되었습니다.");
        }
    }
}
#endif
